DROP TABLE IF EXISTS product CASCADE;

CREATE TABLE product
(   id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    price FLOAT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);